name: Amal Smoke (checkout + setup-python)

on:
  workflow_dispatch:
  issues:
    types: [labeled]

defaults:
  run:
    shell: cmd

permissions:
  contents: read
  issues: write

jobs:
  smoke:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'amal:run')
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verify Python
        run: |
          python -V
          where python

      - name: Create sample_app\app.py
        run: |
          if not exist sample_app mkdir sample_app
          > sample_app\app.py echo print("Hello, Phase 8!")

      - name: Run sample_app
        run: python sample_app\app.py
