name: Amal Orchestrator (Ollama)

on:
  workflow_dispatch:
  issues:
    types: [labeled]

defaults:
  run:
    shell: cmd

permissions:
  contents: write
  issues: write

jobs:
  amal:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'amal:run')
    runs-on: self-hosted
    env:
      OLLAMA_BASE_URL: http://127.0.0.1:11434
      AMAL_MODEL: llama3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Python 3.11 (embeddable)
        run: |
          mkdir tools 2>nul
          curl -L -o tools\py311.zip https://www.python.org/ftp/python/3.11.9/python-3.11.9-embed-amd64.zip
          powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -LiteralPath 'tools\py311.zip' -DestinationPath 'tools\py311' -Force"

      - name: Enable site for embeddable
        run: |
          if exist tools\py311\python311._pth (
            powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content 'tools\\py311\\python311._pth') -replace '^(#\s*)?import site$','import site' | Set-Content 'tools\\py311\\python311._pth' -Encoding ASCII"
            powershell -NoProfile -ExecutionPolicy Bypass -Command "if (-not (Select-String -Path 'tools\\py311\\python311._pth' -Pattern '^import site$')) { Add-Content 'tools\\py311\\python311._pth' 'import site' }"
          )

      - name: Add Python to PATH
        run: echo %CD%\tools\py311>> %GITHUB_PATH%

      - name: Install pip (get-pip.py)
        run: |
          curl -L -o tools\get-pip.py https://bootstrap.pypa.io/get-pip.py
          python tools\get-pip.py --disable-pip-version-check

      - name: Pip install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run orchestrator
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python .amal\orchestrator.py

     # .github/workflows/amal.yml  (замени го последниот чекор)
- name: Commit all changes (status + generated code)
  run: |
    git config user.email "actions@github.com"
    git config user.name "github-actions[bot]"
    git add -A
    git commit -m "Amal: update code and status" || echo "NoChanges"
    git push

