name: Amal Smoke (checkout + embeddable Python)

on:
  workflow_dispatch:
  issues:
    types: [labeled]

defaults:
  run:
    shell: cmd

permissions:
  contents: read
  issues: write

jobs:
  smoke:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'amal:run')
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Python 3.11 (embeddable)
        run: |
          mkdir tools 2>nul
          curl -L -o tools\py311.zip https://www.python.org/ftp/python/3.11.9/python-3.11.9-embed-amd64.zip
          rem Unzip using PowerShell in Bypass mode (allowed even with execution policy restrictions)
          powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -LiteralPath 'tools\py311.zip' -DestinationPath 'tools\py311' -Force"

      - name: Enable site for embeddable (optional but safe)
        run: |
          rem Add 'import site' to enable standard paths if missing
          if exist tools\py311\python311._pth (
            powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content 'tools\\py311\\python311._pth') -replace '^(#\s*)?import site$','import site' | Set-Content 'tools\\py311\\python311._pth' -Encoding ASCII"
            powershell -NoProfile -ExecutionPolicy Bypass -Command "if (-not (Select-String -Path 'tools\\py311\\python311._pth' -Pattern '^import site$')) { Add-Content 'tools\\py311\\python311._pth' 'import site' }"
          )

      - name: Add Python to PATH for this job
        run: |
          echo %CD%\tools\py311>> %GITHUB_PATH%

      - name: Verify Python
        run: |
          python -V
          where python

      - name: Create sample_app\app.py
        run: |
          if not exist sample_app mkdir sample_app
          > sample_app\app.py echo print("Hello, Phase 8!")

      - name: Run sample_app
        run: python sample_app\app.py
