name: Amal Smoke (cmd-only + label trigger)

on:
  workflow_dispatch:
  issues:
    types: [labeled]

defaults:
  run:
    shell: cmd

jobs:
  ping:
    # Пали се или рачно (workflow_dispatch) или кога ќе се додаде label amal:run
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'amal:run')
    runs-on: self-hosted
    steps:
      - name: Echo 1
        run: echo PING_OK

      - name: Print env (cmd)
        run: |
          echo REPO=%GITHUB_REPOSITORY%
          echo EVENT=%GITHUB_EVENT_NAME%
          echo LABEL_NAME=${{ github.event.label.name }}
