name: Amal Smoke (cmd-only)

on:
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  ping:
    runs-on: self-hosted
    steps:
      - name: Echo 1
        run: echo PING_OK

      - name: Print env (cmd)
        run: |
          echo REPO=%GITHUB_REPOSITORY%
          echo EVENT=%GITHUB_EVENT_NAME%
          echo RUNNER_OS=%RUNNER_OS%
